# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

target 'EasyGitHubSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for EasyGitHubSearch
  
  # ui
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.0'

  # rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire', '~> 5.2'

end
